"""empty message

Revision ID: 10db214e0ea
Revises: 32b39839073
Create Date: 2015-11-20 21:49:50.283282

"""

# revision identifiers, used by Alembic.
revision = '10db214e0ea'
down_revision = '32b39839073'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('watching', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'watching')
    ### end Alembic commands ###
