"""empty message

Revision ID: 2e59d536f50
Revises: 1bb76b2ec89
Create Date: 2015-11-13 20:02:20.515352

"""

# revision identifiers, used by Alembic.
revision = '2e59d536f50'
down_revision = '1bb76b2ec89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('season', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'season')
    ### end Alembic commands ###
