"""empty message

Revision ID: 32b39839073
Revises: 7e9f264b0f
Create Date: 2015-11-17 20:21:05.323604

"""

# revision identifiers, used by Alembic.
revision = '32b39839073'
down_revision = '7e9f264b0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shows', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='unique')
    ### end Alembic commands ###
